<a href="https://colab.research.google.com/github/Abhay-Chand/data_science-and-machine-learning/blob/main/new_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
dic1 = {
    "name" :['abhay','garima','ajay','jyoti'],
    "marks":[35,34,36,35],
    "city":['tanakpur','champawat','aao','puri']
}

In [4]:
df = pd.DataFrame(dic1)
df

     name  marks       city
0   abhay     35   tanakpur
1  garima     34  champawat
2    ajay     36        aao
3   jyoti     35       puri

In [5]:
 df.to_csv('friends.csv')

 df.to_csv('friends.csv', index = False)

*   List item
*   List item

In [6]:
 df.to_csv('friends.csv', index = False)

In [7]:
df.head()

     name  marks       city
0   abhay     35   tanakpur
1  garima     34  champawat
2    ajay     36        aao
3   jyoti     35       puri

In [8]:
df.tail(3)

     name  marks       city
1  garima     34  champawat
2    ajay     36        aao
3   jyoti     35       puri

In [9]:
df.describe()

           marks
count   4.000000
mean   35.000000
std     0.816497
min    34.000000
25%    34.750000
50%    35.000000
75%    35.250000
max    36.000000

In [ ]:
olympic24 = pd.read_csv('olympics2024.csv')
olympic24

    Rank        Country Country Code  Gold  Silver  Bronze  Total
0      1  United States           US    40      44      42    126
1      2          China          CHN    40      27      24     91
2      3          Japan          JPN    20      12      13     45
3      4      Australia          AUS    18      19      16     53
4      5         France          FRA    16      26      22     64
..   ...            ...          ...   ...     ...     ...    ...
86    84           Peru          PER     0       0       1      1
87    84          Qatar          QAT     0       0       1      1
88    84      Singapore          SIN     0       0       1      1
89    84       Slovakia          SVK     0       0       1      1
90    84         Zambia          ZAM     0       0       1      1

[91 rows x 7 columns]

In [ ]:
olympic24.head(40)

    Rank         Country Country Code  Gold  Silver  Bronze  Total
0      1   United States           US    40      44      42    126
1      2           China          CHN    40      27      24     91
2      3           Japan          JPN    20      12      13     45
3      4       Australia          AUS    18      19      16     53
4      5          France          FRA    16      26      22     64
5      6     Netherlands          NED    15       7      12     34
6      7   Great Britain          GBG    14      22      29     65
7      8     South Korea          KOR    13       9      10     32
8      9           Italy          ITA    12      13      15     40
9     10         Germany          GER    12      13       8     33
10    11     New Zealand           NZ    10       7       3     20
11    12          Canada          CAN     9       7      11     27
12    13      Uzbekistan          UZB     8       2       3     13
13    14         Hungary          HUN     6       7       6     19
14    15           Spain          SPA     5       4       9     18
15    16          Sweden          SWE     4       4       3     11
16    17           Kenya          KEN     4       2       5     11
17    18          Norway          NOR     4       1       3      8
18    19         Ireland          IRE     4       0       3      7
19    20          Brazil          BRZ     3       7      10     20
20    21            Iran          IRN     3       6       3     12
21    22         Ukraine          UKR     3       5       4     12
22    23         Romania          ROM     3       4       2      9
23    24         Georgia          GEO     3       3       1      7
24    25         Belgium          BEL     3       1       6     10
25    26        Bulgaria          BUL     3       1       3      7
26    27          Serbia          SER     3       1       1      5
27    28  Czech Republic          CZE     3       0       2      5
28    29         Denmark          DEN     2       2       5      9
29    30      Azerbaijan          AZE     2       2       3      7
30    30         Croatia          CRO     2       2       3      7
31    32            Cuba          CUB     2       1       6      9
32    33         Bahrain          BHR     2       1       1      4
33    34        Slovenia          SLO     2       1       0      3
34    35  Chinese Taipei          TPE     2       0       5      7
35    36         Austria          AUT     2       0       3      5
36    37       Hong Kong           HK     2       0       2      4
37    37     Philippines          PHI     2       0       2      4
38    39         Algeria          ALG     2       0       1      3
39    39       Indonesia          IDN     2       0       1      3

In [ ]:
olympic24['Gold'][0] = 100

<ipython-input-47-b376683cc0a4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  olympic24['Gold'][0] = 100

In [ ]:
olympic24['Gold'][24] = 100
olympic24.to_csv('olympic24.csv')

<ipython-input-51-869a032e23fe>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  olympic24['Gold'][24] = 100

In [ ]:
olympic24.describe()

            Rank       Gold     Silver     Bronze       Total
count  91.000000   91.00000  91.000000  91.000000   91.000000
mean   45.307692    5.32967   3.593407   4.219780   11.417582
std    25.652244   15.41504   6.770816   6.558798   19.702829
min     1.000000    0.00000   0.000000   0.000000    1.000000
25%    23.500000    0.00000   0.000000   1.000000    2.000000
50%    44.000000    1.00000   1.000000   2.000000    5.000000
75%    68.000000    3.00000   3.000000   5.000000    9.000000
max    84.000000  100.00000  44.000000  42.000000  126.000000

**NEW FILE**

In [ ]:

newdf = pd.DataFrame(np.random.rand(334,5) , index = np.arange(334))
type(newdf)
newdf

            0         1         2         3         4
0    0.650265  0.770739  0.835295  0.899433  0.507756
1    0.736938  0.053917  0.409837  0.236840  0.492652
2    0.087006  0.664373  0.637313  0.947359  0.222194
3    0.161860  0.460831  0.002746  0.448620  0.474957
4    0.590456  0.624166  0.498611  0.392557  0.202782
..        ...       ...       ...       ...       ...
329  0.912267  0.448412  0.371205  0.549277  0.906690
330  0.508836  0.891376  0.874014  0.492968  0.191894
331  0.500943  0.052208  0.288532  0.897933  0.019238
332  0.426428  0.276659  0.323638  0.557825  0.356680
333  0.167649  0.375387  0.129175  0.644030  0.560966

[334 rows x 5 columns]

In [ ]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.487277    0.472074    0.483652    0.470259    0.493537
std      0.292121    0.295395    0.284144    0.295413    0.284752
min      0.001698    0.000955    0.000341    0.003247    0.000008
25%      0.223110    0.207885    0.266438    0.225787    0.262528
50%      0.484675    0.469057    0.483626    0.437312    0.485483
75%      0.733596    0.761203    0.723477    0.729297    0.733535
max      0.996564    0.999018    0.995776    0.999063    0.995016

In [ ]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
newdf[0][0]= 'abhay'

<ipython-input-71-6400bf9076e5>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'abhay' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]= 'abhay'

In [ ]:
newdf

            0         1         2         3         4
0       abhay  0.770739  0.835295  0.899433  0.507756
1    0.736938  0.053917  0.409837  0.236840  0.492652
2    0.087006  0.664373  0.637313  0.947359  0.222194
3     0.16186  0.460831  0.002746  0.448620  0.474957
4    0.590456  0.624166  0.498611  0.392557  0.202782
..        ...       ...       ...       ...       ...
329  0.912267  0.448412  0.371205  0.549277  0.906690
330  0.508836  0.891376  0.874014  0.492968  0.191894
331  0.500943  0.052208  0.288532  0.897933  0.019238
332  0.426428  0.276659  0.323638  0.557825  0.356680
333  0.167649  0.375387  0.129175  0.644030  0.560966

[334 rows x 5 columns]

In [ ]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [ ]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [ ]:
newdf.to_numpy()

array([['abhay', 0.7707394480214107, 0.835295425234303,
        0.8994329569050129, 0.5077561205743926],
       [0.7369376477458477, 0.05391733158853662, 0.4098372234114238,
        0.23683995895198884, 0.49265177367670754],
       [0.08700555673713462, 0.6643725454505314, 0.6373133650037257,
        0.94735896835843, 0.2221939104702797],
       ...,
       [0.5009425112207712, 0.052208179806436994, 0.2885317214732064,
        0.8979325788308127, 0.019237939074336685],
       [0.42642796983875275, 0.27665931520877696, 0.3236379732057991,
        0.5578249995313314, 0.3566796736892175],
       [0.16764889679912143, 0.37538748796479837, 0.12917465263966732,
        0.6440304040514453, 0.560966138784077]], dtype=object)

In [ ]:
newdf[0][0] = 0.4
newdf

<ipython-input-85-96feb8099be5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf[0][0] = 0.4

            0         1         2         3         4
0         0.4  0.770739  0.835295  0.899433  0.507756
1    0.736938  0.053917  0.409837  0.236840  0.492652
2    0.087006  0.664373  0.637313  0.947359  0.222194
3     0.16186  0.460831  0.002746  0.448620  0.474957
4    0.590456  0.624166  0.498611  0.392557  0.202782
..        ...       ...       ...       ...       ...
329  0.912267  0.448412  0.371205  0.549277  0.906690
330  0.508836  0.891376  0.874014  0.492968  0.191894
331  0.500943  0.052208  0.288532  0.897933  0.019238
332  0.426428  0.276659  0.323638  0.557825  0.356680
333  0.167649  0.375387  0.129175  0.644030  0.560966

[334 rows x 5 columns]

In [ ]:
 newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.4,0.736938,0.087006,0.16186,0.590456,0.177866,0.996964,0.420739,0.319736,0.389111,...,0.738577,0.869214,0.372419,0.536743,0.171766,0.912267,0.508836,0.500943,0.426428,0.167649
1,0.770739,0.053917,0.664373,0.460831,0.624166,0.773412,0.621171,0.533119,0.452981,0.595658,...,0.346461,0.698353,0.85358,0.1589,0.761331,0.448412,0.891376,0.052208,0.276659,0.375387
2,0.835295,0.409837,0.637313,0.002746,0.498611,0.807779,0.806449,0.854857,0.710712,0.287632,...,0.123659,0.980717,0.01187,0.409123,0.619234,0.371205,0.874014,0.288532,0.323638,0.129175
3,0.899433,0.23684,0.947359,0.44862,0.392557,0.057744,0.68138,0.94127,0.047206,0.363693,...,0.728843,0.357457,0.673079,0.608012,0.282989,0.549277,0.492968,0.897933,0.557825,0.64403
4,0.507756,0.492652,0.222194,0.474957,0.202782,0.034967,0.033483,0.245174,0.301712,0.559516,...,0.914265,0.570529,0.212107,0.314151,0.096876,0.90669,0.191894,0.019238,0.35668,0.560966